/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "LedFunctions.h"
#include "UARTSender.h"

#define RCC_ADRESS 0x40023800
#define UART_4_ADRESS 0x40004C00
#define GPIOA_ADRESS 0x40020000
#define NVIC_ADRESS  0xE000E100
#define UART4_IRQN 52


volatile uint32_t *const UART4_DR=(uint32_t *)(UART_4_ADRESS+0x04);

int main(void)
{
	LedInit();

	volatile uint32_t *const RCC_AHB1ENR=(uint32_t *)(RCC_ADRESS+0x30);
	volatile uint32_t *const GPIOA_MODER=(uint32_t*) (GPIOA_ADRESS+0x00);
	volatile uint32_t *const GPIOA_AFRL=(uint32_t*) (GPIOA_ADRESS+0x20);
	volatile uint32_t *const RCC_APB1ENR=(uint32_t *)(RCC_ADRESS+0x40);
	volatile uint32_t *const UART4_BRR=(uint32_t *)(UART_4_ADRESS+ 0x08);
	volatile uint32_t *const UART4_CR1=(uint32_t *)(UART_4_ADRESS+ 0x0C);
	volatile uint32_t *const NVIC_ISER1=(uint32_t *)(0xE000E100+0x4);


	*RCC_AHB1ENR|=0x1;//clock for GPIOA

	*GPIOA_MODER&=~(0xF);
	*GPIOA_MODER|=0xA;//changing PA0 and PA1 mode to alternate function mode

	*GPIOA_AFRL&=~(0xFF);
	*GPIOA_AFRL|=0x88; //Configure PA0 and PA1 to AF8 (UART4 TX/RX)

	*RCC_APB1ENR|=(0x1<<19);//clock for UART4

	*UART4_BRR = 0x8B; // Set baud rate to 115200 bps
	*UART4_CR1 |= (1 << 13); // UE: USART/UART enable
	*UART4_CR1 |= (1 << 2); // RE: Receiver enable
	*UART4_CR1 |= (1 << 3); // TE: Transmitter enable
	*UART4_CR1 |= (1 << 5); // RXNEIE: interrupt when receive data register not empty

	*NVIC_ISER1|=(1<<(UART4_IRQN%32));

    /* Loop forever */
	for(;;);
}



volatile uint32_t irq_hit = 0;
int i=0;
char buffer[50]={};

void UART4_IRQHandler(void)
{
	volatile uint8_t c = (uint8_t)(*UART4_DR & 0xFF);
	if(c!='\n' && c!='\r'){
		buffer[i]=c;
		i++;
	}
	else{
		buffer[i]='\0';
		if(!strcmp(buffer,"LED ON")){
			turnOnBlueLED();
			sendLedOn();

		}
		else if(!strcmp(buffer,"LED OFF")){
			turnOffBlueLED();
			sendLedOff();
		}
		buffer[0]='\0';
		i=0;
	}


}




